export const SHOW_CALL_MODAL = 'SHOW_CALL_MODAL';
export const HIDE_CALL_MODAL = 'HIDE_CALL_MODAL';
export const SHOW_SEND_MODAL = 'SHOW_SEND_MODAL';
export const HIDE_SEND_MODAL = 'HIDE_SEND_MODAL';

export const SHOW_LOADING_REQUEST = 'SHOW_LOADING_REQUEST';
export const HIDE_LOADING_REQUEST = 'SHOW_LOADING_REQUEST';
export const ERROR_LOADING_REQUEST = 'ERROR_LOADING_REQUEST';
